# Generated by Django 4.1.6 on 2023-02-10 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Bmi",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("bmitype", models.CharField(max_length=100)),
                ("bmidescription", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="FoodTips",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("foodname", models.CharField(max_length=100)),
                ("foodnutrations", models.TextField()),
                ("fooddescriptions", models.TextField()),
                ("fooddanger", models.TextField()),
                ("whocaneat", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="SignUp",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fname", models.CharField(max_length=100)),
                ("uname", models.CharField(max_length=100)),
                ("dob", models.CharField(max_length=100)),
                ("gender", models.CharField(max_length=100)),
                ("umail", models.CharField(max_length=100)),
                ("pnumber", models.CharField(max_length=100)),
                ("pass1", models.CharField(max_length=100)),
                ("pass2", models.CharField(max_length=100)),
                
            ],
        ),
    ]
