# Generated by Django 4.1.6 on 2023-02-12 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0003_rename_description_signup_description"),
    ]

    operations = [
        migrations.CreateModel(
            name="Update",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("bmi", models.CharField(max_length=100)),
                ("bp", models.CharField(max_length=100)),
                ("bs", models.CharField(max_length=100)),
            ],
        ),
    ]
