# Generated by Django 4.1.6 on 2023-02-12 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0004_update"),
    ]

    operations = [
        migrations.AddField(
            model_name="update",
            name="unamep",
            field=models.CharField(max_length=100, null=True),
        ),
    ]
