# Generated by Django 4.1.6 on 2023-02-13 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0005_update_unamep"),
    ]

    operations = [
        migrations.CreateModel(
            name="FoodBlog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=250)),
                ("description", models.TextField()),
                ("writter", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="HealthBlog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=250)),
                ("description", models.TextField()),
                ("writter", models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name="update",
            name="bmi",
            field=models.CharField(default="0", max_length=100),
        ),
        migrations.AlterField(
            model_name="update",
            name="bp",
            field=models.CharField(default="0", max_length=100),
        ),
        migrations.AlterField(
            model_name="update",
            name="bs",
            field=models.CharField(default="0", max_length=100),
        ),
    ]
