# Generated by Django 4.1.6 on 2023-02-13 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0006_foodblog_healthblog_alter_update_bmi_alter_update_bp_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="foodblog",
            name="slug",
            field=models.SlugField(null=True, unique=True),
        ),
        migrations.AddField(
            model_name="healthblog",
            name="slug",
            field=models.SlugField(null=True, unique=True),
        ),
    ]
